#
# Module manifest for module 'Az.Resources'
#
# Generated by: Microsoft Corporation
#
# Generated on: 4/29/2026
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'Az.Resources.psm1'

# Version number of this module.
ModuleVersion = '9.1.0'

# Supported PSEditions
CompatiblePSEditions = 'Core', 'Desktop'

# ID used to uniquely identify this module
GUID = '48bb344d-4c24-441e-8ea0-589947784700'

# Author of this module
Author = 'Microsoft Corporation'

# Company or vendor of this module
CompanyName = 'Microsoft Corporation'

# Copyright statement for this module
Copyright = 'Microsoft Corporation. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Microsoft Azure PowerShell - Azure Resource Manager and Active Directory cmdlets in Windows PowerShell and PowerShell Core.  Manages subscriptions, tenants, resource groups, deployment templates, providers, and resource permissions in Azure Resource Manager.  Provides cmdlets for managing resources generically across resource providers.
For more information on Resource Manager, please visit the following: https://learn.microsoft.com/azure/azure-resource-manager/
For more information on Active Directory, please visit the following: https://learn.microsoft.com/azure/active-directory/fundamentals/active-directory-whatis'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
DotNetFrameworkVersion = '4.7.2'

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
RequiredAssemblies = 'Authorization.Autorest/bin/Az.Authorization.private.dll', 
               'DataBoundary.Autorest/bin/Az.DataBoundary.private.dll', 
               'Microsoft.Azure.Management.ManagementGroups.dll', 
               'Microsoft.Azure.Management.ResourceManager.dll', 
               'Microsoft.Azure.PowerShell.Authorization.Management.Sdk.dll', 
               'Microsoft.Azure.PowerShell.Resources.Management.Sdk.dll', 
               'Microsoft.Extensions.Caching.Abstractions.dll', 
               'Microsoft.Extensions.Caching.Memory.dll', 
               'Microsoft.Extensions.DependencyInjection.Abstractions.dll', 
               'Microsoft.Extensions.Options.dll', 
               'Microsoft.Extensions.Primitives.dll', 
               'MSGraph.Autorest/bin/Az.MSGraph.private.dll', 
               'Policy.Autorest/bin/Az.Policy.private.dll', 
               'System.Runtime.CompilerServices.Unsafe.dll'

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = 'Authorization.Autorest/Az.Authorization.format.ps1xml', 
               'DataBoundary.Autorest/Az.DataBoundary.format.ps1xml', 
               'MSGraph.Autorest/Az.MSGraph.format.ps1xml', 
               'Policy.Autorest/Az.Policy.format.ps1xml', 
               'ResourceManager.format.ps1xml', 
               'ResourceManager.generated.format.ps1xml', 
               'Resources.format.ps1xml', 'Tags.format.ps1xml'

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
NestedModules = @('Authorization.Autorest/Az.Authorization.psm1', 'DataBoundary.Autorest/Az.DataBoundary.psm1', 'MSGraph.Autorest/Az.MSGraph.psm1', 'Policy.Autorest/Az.Policy.psm1')

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = 'Add-AzADAppPermission', 'Add-AzADGroupMember', 
               'Get-AzADAppCredential', 'Get-AzADAppFederatedCredential', 
               'Get-AzADApplication', 'Get-AzADAppPermission', 'Get-AzADGroup', 
               'Get-AzADGroupMember', 'Get-AzADGroupOwner', 'Get-AzADOrganization', 
               'Get-AzADServicePrincipal', 
               'Get-AzADServicePrincipalAppRoleAssignment', 'Get-AzADSpCredential', 
               'Get-AzADUser', 'Get-AzDataBoundaryScope', 'Get-AzDataBoundaryTenant', 
               'Get-AzPolicyAssignment', 'Get-AzPolicyDefinition', 
               'Get-AzPolicyExemption', 'Get-AzPolicySetDefinition', 
               'Get-AzRoleAssignmentSchedule', 
               'Get-AzRoleAssignmentScheduleInstance', 
               'Get-AzRoleAssignmentScheduleRequest', 
               'Get-AzRoleEligibilitySchedule', 
               'Get-AzRoleEligibilityScheduleInstance', 
               'Get-AzRoleEligibilityScheduleRequest', 
               'Get-AzRoleEligibleChildResource', 'Get-AzRoleManagementPolicy', 
               'Get-AzRoleManagementPolicyAssignment', 'New-AzADAppCredential', 
               'New-AzADAppFederatedCredential', 'New-AzADApplication', 
               'New-AzADGroup', 'New-AzADGroupOwner', 'New-AzADServicePrincipal', 
               'New-AzADServicePrincipalAppRoleAssignment', 'New-AzADSpCredential', 
               'New-AzADUser', 'New-AzPolicyAssignment', 'New-AzPolicyDefinition', 
               'New-AzPolicyExemption', 'New-AzPolicySetDefinition', 
               'New-AzRoleAssignmentScheduleRequest', 
               'New-AzRoleEligibilityScheduleRequest', 
               'New-AzRoleManagementPolicyAssignment', 'Remove-AzADAppCredential', 
               'Remove-AzADAppFederatedCredential', 'Remove-AzADApplication', 
               'Remove-AzADAppPermission', 'Remove-AzADGroup', 
               'Remove-AzADGroupMember', 'Remove-AzADGroupOwner', 
               'Remove-AzADServicePrincipal', 
               'Remove-AzADServicePrincipalAppRoleAssignment', 
               'Remove-AzADSpCredential', 'Remove-AzADUser', 
               'Remove-AzPolicyAssignment', 'Remove-AzPolicyDefinition', 
               'Remove-AzPolicyExemption', 'Remove-AzPolicySetDefinition', 
               'Remove-AzRoleManagementPolicy', 
               'Remove-AzRoleManagementPolicyAssignment', 'Set-AzDataBoundary', 
               'Stop-AzRoleAssignmentScheduleRequest', 
               'Stop-AzRoleEligibilityScheduleRequest', 
               'Update-AzADAppFederatedCredential', 'Update-AzADApplication', 
               'Update-AzADGroup', 'Update-AzADServicePrincipal', 
               'Update-AzADServicePrincipalAppRoleAssignment', 'Update-AzADUser', 
               'Update-AzPolicyAssignment', 'Update-AzPolicyDefinition', 
               'Update-AzPolicyExemption', 'Update-AzPolicySetDefinition', 
               'Update-AzRoleAssignmentScheduleRequest', 
               'Update-AzRoleEligibilityScheduleRequest', 
               'Update-AzRoleManagementPolicy', 
               'Update-AzRoleManagementPolicyAssignment'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = 'Export-AzResourceGroup', 'Export-AzTemplateSpec', 
               'Get-AzDenyAssignment', 'Get-AzDeployment', 
               'Get-AzDeploymentOperation', 'Get-AzDeploymentScript', 
               'Get-AzDeploymentScriptLog', 'Get-AzDeploymentWhatIfResult', 
               'Get-AzLocation', 'Get-AzManagedApplication', 
               'Get-AzManagedApplicationDefinition', 'Get-AzManagementGroup', 
               'Get-AzManagementGroupDeployment', 
               'Get-AzManagementGroupDeploymentOperation', 
               'Get-AzManagementGroupDeploymentStack', 
               'Get-AzManagementGroupDeploymentWhatIfResult', 
               'Get-AzManagementGroupEntity', 
               'Get-AzManagementGroupHierarchySetting', 
               'Get-AzManagementGroupNameAvailability', 
               'Get-AzManagementGroupSubscription', 'Get-AzPolicyAlias', 
               'Get-AzPrivateLinkAssociation', 'Get-AzProviderFeature', 
               'Get-AzProviderOperation', 'Get-AzProviderPreviewFeature', 
               'Get-AzResource', 'Get-AzResourceGroup', 
               'Get-AzResourceGroupDeployment', 
               'Get-AzResourceGroupDeploymentOperation', 
               'Get-AzResourceGroupDeploymentStack', 
               'Get-AzResourceGroupDeploymentWhatIfResult', 'Get-AzResourceLock', 
               'Get-AzResourceManagementPrivateLink', 'Get-AzResourceProvider', 
               'Get-AzRoleAssignment', 'Get-AzRoleDefinition', 
               'Get-AzSubscriptionDeploymentStack', 'Get-AzTag', 
               'Get-AzTemplateSpec', 'Get-AzTenantBackfillStatus', 
               'Get-AzTenantDeployment', 'Get-AzTenantDeploymentOperation', 
               'Get-AzTenantDeploymentWhatIfResult', 'Invoke-AzResourceAction', 
               'Move-AzResource', 'New-AzDenyAssignment', 'New-AzDeployment', 
               'New-AzManagedApplication', 'New-AzManagedApplicationDefinition', 
               'New-AzManagementGroup', 'New-AzManagementGroupDeployment', 
               'New-AzManagementGroupDeploymentStack', 
               'New-AzManagementGroupHierarchySetting', 
               'New-AzManagementGroupSubscription', 'New-AzPrivateLinkAssociation', 
               'New-AzResource', 'New-AzResourceGroup', 
               'New-AzResourceGroupDeployment', 
               'New-AzResourceGroupDeploymentStack', 'New-AzResourceLock', 
               'New-AzResourceManagementPrivateLink', 'New-AzRoleAssignment', 
               'New-AzRoleDefinition', 'New-AzSubscriptionDeploymentStack', 
               'New-AzTag', 'New-AzTemplateSpec', 'New-AzTenantDeployment', 
               'Publish-AzBicepModule', 'Register-AzProviderFeature', 
               'Register-AzProviderPreviewFeature', 'Register-AzResourceProvider', 
               'Remove-AzDeployment', 'Remove-AzDeploymentScript', 
               'Remove-AzDenyAssignment', 'Remove-AzManagedApplication', 
               'Remove-AzManagedApplicationDefinition', 'Remove-AzManagementGroup', 
               'Remove-AzManagementGroupDeployment', 
               'Remove-AzManagementGroupDeploymentStack', 
               'Remove-AzManagementGroupHierarchySetting', 
               'Remove-AzManagementGroupSubscription', 
               'Remove-AzPrivateLinkAssociation', 'Remove-AzResource', 
               'Remove-AzResourceGroup', 'Remove-AzResourceGroupDeployment', 
               'Remove-AzResourceGroupDeploymentStack', 'Remove-AzResourceLock', 
               'Remove-AzResourceManagementPrivateLink', 'Remove-AzRoleAssignment', 
               'Remove-AzRoleDefinition', 'Remove-AzSubscriptionDeploymentStack', 
               'Remove-AzTag', 'Remove-AzTemplateSpec', 'Remove-AzTenantDeployment', 
               'Save-AzDeploymentScriptLog', 'Save-AzDeploymentTemplate', 
               'Save-AzManagementGroupDeploymentStackTemplate', 
               'Save-AzManagementGroupDeploymentTemplate', 
               'Save-AzResourceGroupDeploymentStackTemplate', 
               'Save-AzResourceGroupDeploymentTemplate', 
               'Save-AzSubscriptionDeploymentStackTemplate', 
               'Save-AzTenantDeploymentTemplate', 'Set-AzManagedApplication', 
               'Set-AzManagedApplicationDefinition', 
               'Set-AzManagementGroupDeploymentStack', 'Set-AzResource', 
               'Set-AzResourceGroup', 'Set-AzResourceGroupDeploymentStack', 
               'Set-AzResourceLock', 'Set-AzRoleAssignment', 'Set-AzRoleDefinition', 
               'Set-AzSubscriptionDeploymentStack', 'Set-AzTemplateSpec', 
               'Start-AzTenantBackfill', 'Stop-AzDeployment', 
               'Stop-AzManagementGroupDeployment', 
               'Stop-AzResourceGroupDeployment', 'Stop-AzTenantDeployment', 
               'Test-AzDeployment', 'Test-AzManagementGroupDeployment', 
               'Test-AzManagementGroupDeploymentStack', 
               'Test-AzResourceGroupDeployment', 
               'Test-AzResourceGroupDeploymentStack', 
               'Test-AzSubscriptionDeploymentStack', 'Test-AzTenantDeployment', 
               'Unregister-AzProviderFeature', 
               'Unregister-AzProviderPreviewFeature', 
               'Unregister-AzResourceProvider', 'Update-AzManagementGroup', 
               'Update-AzManagementGroupHierarchySetting', 'Update-AzTag'

# Variables to export from this module
# VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = 'Get-AzADServicePrincipalCredential', 
               'Get-AzResourceProviderAction', 'Get-AzSubscriptionDeployment', 
               'Get-AzSubscriptionDeploymentOperation', 
               'Get-AzSubscriptionDeploymentWhatIfResult', 
               'New-AzADServicePrincipalCredential', 
               'New-AzSubscriptionDeployment', 
               'Remove-AzADServicePrincipalCredential', 
               'Remove-AzSubscriptionDeployment', 
               'Save-AzSubscriptionDeploymentTemplate', 'Set-AzADApplication', 
               'Set-AzADServicePrincipal', 'Set-AzADUser', 'Set-AzPolicyAssignment', 
               'Set-AzPolicyDefinition', 'Set-AzPolicyExemption', 
               'Set-AzPolicySetDefinition', 'Stop-AzSubscriptionDeployment', 
               'Test-AzSubscriptionDeployment'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
ModuleList = @(@{ModuleName = 'Az.Accounts'; ModuleVersion = '5.4.0'; })

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'Azure','ResourceManager','ARM','Provider','ResourceGroup','Deployment','ActiveDirectory','Authorization','Management','ManagementGroups','Tags'

        # A URL to the license for this module.
        LicenseUri = 'https://aka.ms/azps-license'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/Azure/azure-powershell'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = '* Made ''Remove-AzDenyAssignment'' honor ''-Confirm:False'' and idempotent when no matching deny assignment exists. The redundant ''-Force'' switch was removed (the cmdlet relies on the standard ''SupportsShouldProcess''/''ConfirmImpact'' pattern).
* Improved error messages for role assignment and role definition operations to include the underlying service error code and message instead of just the HTTP status code. [#19605] [#19374]
* Added ''-PrincipalId'' and ''-PrincipalType'' to ''New-AzDenyAssignment'' to support per-principal deny assignments targeting a specific User or ServicePrincipal, in addition to the existing Everyone mode.
* Added ''New-AzDenyAssignment'' for creating user-assigned deny assignments using the ''2024-07-01-preview'' API. Deny assignments allow denying specific write, delete, and action operations to all principals at a given scope while excluding specified principals.
* Added ''Remove-AzDenyAssignment'' for removing user-assigned deny assignments by ID, name and scope, or pipeline input.
* Regenerated Authorization Management SDK from ''2024-07-01-preview'' swagger specification to include deny assignment create and delete operations.
* Fixed ''New-AzDeployment'' not reporting nested ARM (Azure Resource Manager) error details (e.g. ''KeyVaultParameterReferenceSecretRetrieveFailed'') when a ''MultipleErrorsOccurred'' validation failure is returned. Previously, the inner errors were silently dropped and only the generic top-level error was shown. [#28308]'

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

 } # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}


# SIG # Begin signature block
# MIInSQYJKoZIhvcNAQcCoIInOjCCJzYCAQExDzANBglghkgBZQMEAgEFADB5Bgor
# BgEEAYI3AgEEoGswaTA0BgorBgEEAYI3AgEeMCYCAwEAAAQQH8w7YFlLCE63JNLG
# KX7zUQIBAAIBAAIBAAIBAAIBADAxMA0GCWCGSAFlAwQCAQUABCB+FJsi35GH0YpR
# y7ycAUJvnmgC7J2sTEHDRpz4Sai3nKCCDLowggX1MIID3aADAgECAhMzAAACHU0Z
# yE7XD1dIAAAAAAIdMA0GCSqGSIb3DQEBCwUAMFcxCzAJBgNVBAYTAlVTMR4wHAYD
# VQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMTH01pY3Jvc29mdCBD
# b2RlIFNpZ25pbmcgUENBIDIwMjQwHhcNMjYwNDE2MTg1OTQzWhcNMjcwNDE1MTg1
# OTQzWjB0MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UE
# BxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMR4wHAYD
# VQQDExVNaWNyb3NvZnQgQ29ycG9yYXRpb24wggEiMA0GCSqGSIb3DQEBAQUAA4IB
# DwAwggEKAoIBAQDQvewXxx9gZZFC6Ys1WBay8BJ8kGA4JQnH5CMafqOASlTpK9H8
# o5ZXTXt0caVQTNMUPt445wXYD+dFtaKWTwDn1I52oUSrC9vJin1Gsqt+zyKJL5Dg
# 3eQXbQNR61DmMy20GLTIO3SFed9Rfi/ophgCLGFLDR3r0KvHjwMb/jYWS0celV/4
# Lz27LfAekm8v9E5IXaeiXbAUYZKK090n4CVl3JBtbN+9DtI9SNu/yjvozW52/u7R
# X/Ttpa/KDlpuokZ+Zcbvmtd9ur9gFLvZzh41o9MsE/clQtdaFWGvuo6Jua/ntpgk
# ey3E5/vBFe+MJPG6phdnuo6r57ZudCudiI1bAgMBAAGjggGbMIIBlzAOBgNVHQ8B
# Af8EBAMCB4AwHwYDVR0lBBgwFgYKKwYBBAGCN0wIAQYIKwYBBQUHAwMwHQYDVR0O
# BBYEFH6QuMwqcPG0hQlQ6c5jCtTTLrVeMEUGA1UdEQQ+MDykOjA4MR4wHAYDVQQL
# ExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xFjAUBgNVBAUTDTIzMDAxMis1MDc1NTkw
# HwYDVR0jBBgwFoAUf1k/VCHarU/vBeXmo9ctBpQSCDEwYAYDVR0fBFkwVzBVoFOg
# UYZPaHR0cDovL3d3dy5taWNyb3NvZnQuY29tL3BraW9wcy9jcmwvTWljcm9zb2Z0
# JTIwQ29kZSUyMFNpZ25pbmclMjBQQ0ElMjAyMDI0LmNybDBtBggrBgEFBQcBAQRh
# MF8wXQYIKwYBBQUHMAKGUWh0dHA6Ly93d3cubWljcm9zb2Z0LmNvbS9wa2lvcHMv
# Y2VydHMvTWljcm9zb2Z0JTIwQ29kZSUyMFNpZ25pbmclMjBQQ0ElMjAyMDI0LmNy
# dDAMBgNVHRMBAf8EAjAAMA0GCSqGSIb3DQEBCwUAA4ICAQBKTbYOjzwTG/DXGaz9
# s6+fQeaTtDcFmMY+5UyVFCyj7Pv+5i37qfX8lSL/tBIfYQfWsMuBQlfZurJD6r4H
# VJ2CeH+1fgiq8dcHdVKoZ3Sa2qXoX3cq9iS8cVb06B7+5/XJ7I0OxHH9fDsvJ3T3
# w5V/ZtAIFmLrl+P0CtG+92uzRsn0nTbdFjOkLMLWPLAU3THohKRlSEMgFJpPkm5n
# 5UAZ35xX6FWCrDLsSKb555bTifwa8mJBwdlof0bmfYidH+dxZ1FdDxvLnNl9zeKs
# A4kejaaIqqIPguhwAti5Ql7BlTNoJNwxCvBmqW2MQLnCkYN/VVUsR3V2x/rcTNzo
# Bf/Z/SpROvdaA2ZOOd1uioXJt3tdLQ7vHpqpib0KfWr/FWXW10q38VxfCnRQBqzb
# SuztR7nEMuzX7Ck+B/XaPDXd1qh72+QYyB0Z2VzWmO9zsnb9Uq/dwu8LGeQqnyu6
# 7SDGACvnXii2fb9+US492VTnXSnFKyqwgzUyFMtZK1/sHYTv6bG4TtQUygQxTN+Z
# V+aJIlKO2MqZ7bKrAnOzS9m6NgoTdWOq11bTOZwKlIEV/EhV9SWkDmdpR/hPPT2v
# 6TEj4F8PT/zHjRezIU5c/DGlt/VhY/pK0XkJtEyMmmS1BMtjU/rqBZVMIm3dnxQs
# /TBByr+Cf8Z1r7aifQVQ+WSqzjCCBr0wggSloAMCAQICEzMAAAA5O7Y3Gb8GHWcA
# AAAAADkwDQYJKoZIhvcNAQEMBQAwgYgxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpX
# YXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQg
# Q29ycG9yYXRpb24xMjAwBgNVBAMTKU1pY3Jvc29mdCBSb290IENlcnRpZmljYXRl
# IEF1dGhvcml0eSAyMDExMB4XDTI0MDgwODIwNTQxOFoXDTM2MDMyMjIyMTMwNFow
# VzELMAkGA1UEBhMCVVMxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEo
# MCYGA1UEAxMfTWljcm9zb2Z0IENvZGUgU2lnbmluZyBQQ0EgMjAyNDCCAiIwDQYJ
# KoZIhvcNAQEBBQADggIPADCCAgoCggIBANgBnB7jOMeqlRYHNa265v4IY9fH8TKh
# emHfPINe1gpLaV3dhg324WwH06LcHbpnsBukCDNitryo0dtS/EW6I/yEL/bLSY8h
# KpbfQuWusBPr9qazYcDxCW/qnjb5JsI1s8bNOg3bVATvQVL4tcf03aTycsz8QeCd
# M0l/yHRObJ9QqazM1r6VPEOJ7LL+uEEb73w6QCuhs89a1uv1zerOYMnsneRRwCbp
# yW11IcggU0cRKDDq1pjVJzIbIF6+oiXXbReOsgeI8zu1FyQfK0fVkaya8SmVHQ/t
# Of23mZ4W9k0Ri22QW9p3UgSC5OUDktKxxcCmGL6tXLfOGSWHIIV4YrTJTT6PNty5
# REojHJuZHArkF9VnHTERWoTjAzfI3kP+5b4alUdhgAZ7ttOu1bVnXfHaqPYl2rPs
# 20ji03LOVWsh/radgE17es5hL+t6lV0eVHrVhsssROWJuz2MXMCt7iw7lFPG9LXK
# Gjsmonn2gotGdHIuEg5JnJMJVmixd5LRlkmgYRZKzhxSCwyoGIq0PhaA7Y+VPct5
# pCHkijcIIDm0nlkK+0KyepolcqGm0T/GYQRMhHJlGOOmVQop36wUVUYklUy++vDW
# eEgEo4s7hxN6mIbf2MSIQ/iIfMZgJxC69oukMUXCrOC3SkE/xIkgpfl22MM1itkZ
# 35nNXkMolU1lAgMBAAGjggFOMIIBSjAOBgNVHQ8BAf8EBAMCAYYwEAYJKwYBBAGC
# NxUBBAMCAQAwHQYDVR0OBBYEFH9ZP1Qh2q1P7wXl5qPXLQaUEggxMBkGCSsGAQQB
# gjcUAgQMHgoAUwB1AGIAQwBBMA8GA1UdEwEB/wQFMAMBAf8wHwYDVR0jBBgwFoAU
# ci06AjGQQ7kUBU7h6qfHMdEjiTQwWgYDVR0fBFMwUTBPoE2gS4ZJaHR0cDovL2Ny
# bC5taWNyb3NvZnQuY29tL3BraS9jcmwvcHJvZHVjdHMvTWljUm9vQ2VyQXV0MjAx
# MV8yMDExXzAzXzIyLmNybDBeBggrBgEFBQcBAQRSMFAwTgYIKwYBBQUHMAKGQmh0
# dHA6Ly93d3cubWljcm9zb2Z0LmNvbS9wa2kvY2VydHMvTWljUm9vQ2VyQXV0MjAx
# MV8yMDExXzAzXzIyLmNydDANBgkqhkiG9w0BAQwFAAOCAgEAFJQfOChP7onn6fLI
# MKrSlN1WYKwDFgAddymOUO3FrM8d7B/W/iQ6DxXsDn7D5W4wMwYeLystcEqfkjz4
# NURRgazyMu5yRzQh4LqjA4tStTcJh1opExo7nn5PuPBYnbu0+THSuVHTe0VTTPVh
# ily/piFrDo3axQ9P4C+Ol5yet+2gTfekICS5xS+cYfSIvgn0JksVBVMYVI5QFu/q
# hnLhsEFEUzG8fvv0hjgkO+lkpV9ty6GkN4vdnd7ya6Q6aR9y34aiM1qmxaxBi6OU
# nyNl6fkuun/diTFnYDLTppOkr/mg5WSfCiDVMNCxtj4wPKC5OmHm1DQIt/MNokbb
# H3UGsFP1QbzsLocuSqLCvH09Io3fDPTmscR9Y75G4qX7RTX8AdBPo0I6OEojf39z
# uFZt0qOHm65YWQE69cZM2ueE1MB05dNNgHK9gTE7zKvK/fg8B2qjW88MT/WF5V5u
# vZGtqa9FSL2RazArA+rDPuf6JGYz4HpgMZHB4S6szWSKYBv0VisCzfxgeU+dquXW
# 9bd0auYlOB58DPcOYKdc3Se94g+xL4pcEhbB54JOgAkwYTu/9dLeH2pDqeJZAABV
# DWRQCaXfO5LgyKwKCLYXpigrZYCjUSBcr+Ve8PFWMhVTQl0v4q8J/AUmQN5W4n10
# 1cY2L4A7GTQG1h32HHAvfQESWP0xghnlMIIZ4QIBATBuMFcxCzAJBgNVBAYTAlVT
# MR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMTH01pY3Jv
# c29mdCBDb2RlIFNpZ25pbmcgUENBIDIwMjQCEzMAAAIdTRnITtcPV0gAAAAAAh0w
# DQYJYIZIAWUDBAIBBQCgga4wGQYJKoZIhvcNAQkDMQwGCisGAQQBgjcCAQQwHAYK
# KwYBBAGCNwIBCzEOMAwGCisGAQQBgjcCARUwLwYJKoZIhvcNAQkEMSIEICnCb0Pw
# hqicAGVvOJ2rLzrWU2c3j0zMetRUJIVYaqXJMEIGCisGAQQBgjcCAQwxNDAyoBSA
# EgBNAGkAYwByAG8AcwBvAGYAdKEagBhodHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20w
# DQYJKoZIhvcNAQEBBQAEggEAXkI/y3B9JN4+jrP/+GEgCur1ClyqXAoUsp5rGNQZ
# oQI7jbhlpiQmLU8lIu4YlAV70BYHz04bHBRWw70o4wCgYxILZL6+frR32TirnmgL
# m+Ptz38BLpHF68lT4+nXzqntzb4eyY++VkfFBB0qc4C77jis5eFUvQhyp0t8vEbR
# Baqqqz8ml/gK869+oNjEqlEY8xSNDxZ173ByXeEnv/gGIXLj4RewkSqgzzbO/y7f
# MpywJ6p1xpCRgofO1nIkUNGS07tQdsecOtaCSKPNiZ0Mf46fFzo9IW7zT4yBRPbo
# tfnovAElCIgmzLBVyYVuuNznWOGPTJRStxt8OPyauLA+O6GCF5cwgheTBgorBgEE
# AYI3AwMBMYIXgzCCF38GCSqGSIb3DQEHAqCCF3AwghdsAgEDMQ8wDQYJYIZIAWUD
# BAIBBQAwggFSBgsqhkiG9w0BCRABBKCCAUEEggE9MIIBOQIBAQYKKwYBBAGEWQoD
# ATAxMA0GCWCGSAFlAwQCAQUABCCG/GjaQvCMI0JMfPcxJEkPREt/ysRHJRHYni+u
# Ek2CsgIGaedu0zW2GBMyMDI2MDQyOTEwNDkxOS4wNzdaMASAAgH0oIHRpIHOMIHL
# MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVk
# bW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSUwIwYDVQQLExxN
# aWNyb3NvZnQgQW1lcmljYSBPcGVyYXRpb25zMScwJQYDVQQLEx5uU2hpZWxkIFRT
# UyBFU046QTkzNS0wM0UwLUQ5NDcxJTAjBgNVBAMTHE1pY3Jvc29mdCBUaW1lLVN0
# YW1wIFNlcnZpY2WgghHtMIIHIDCCBQigAwIBAgITMwAAAifVwIPDsS5XLQABAAAC
# JzANBgkqhkiG9w0BAQsFADB8MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGlu
# Z3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBv
# cmF0aW9uMSYwJAYDVQQDEx1NaWNyb3NvZnQgVGltZS1TdGFtcCBQQ0EgMjAxMDAe
# Fw0yNjAyMTkxOTQwMDRaFw0yNzA1MTcxOTQwMDRaMIHLMQswCQYDVQQGEwJVUzET
# MBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMV
# TWljcm9zb2Z0IENvcnBvcmF0aW9uMSUwIwYDVQQLExxNaWNyb3NvZnQgQW1lcmlj
# YSBPcGVyYXRpb25zMScwJQYDVQQLEx5uU2hpZWxkIFRTUyBFU046QTkzNS0wM0Uw
# LUQ5NDcxJTAjBgNVBAMTHE1pY3Jvc29mdCBUaW1lLVN0YW1wIFNlcnZpY2UwggIi
# MA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQDixWy1fDOSL4qj3A1pady+elID
# LwnF3UuLzJIOWwGHcEgrxxwtnyviUIDmmxylTUl1u+2rBPp2zT4BwwQhvGaJpExq
# vPLlDFlbfmSflKI86eFqofiZ7j8NTRO4l7wGg9Njm+muNauTcFW2qdfIjKE950Ok
# rm9MnMOGYy+fibNYdxTPRPq1T4MLZK3s3vdMyMEOldcOQkSKpxD6/1Gk6gOmCu2K
# gI8f0ex6vYxnKDl9W0OLSEa/6y82oIbsm+1QBifOQ47xWKTG1CmvtGr85LzA75/M
# AcUmRw5/of/qET0UFV1WulMcJrI6DASAsNCNB+6WLrotuBZAj+VMlqbn5RMZ6Q4I
# Y7JwaAiIXh7VjxrnwUOYZG8WEGhfrA98di+7LEn9AqvvEOyG+UQcjVhCCbMGXigJ
# XSApeyeWupCsD0jgQMNCxfB5BLBDWxgdY3dJBEPgxfkgTDQLBggtVv2d5CYxHKgI
# ItB4bI5eSb5jkIG2WotnFetT0legpw/Eozwf39ao6tENY21eVWIzRw/GsmvwjYQF
# 6vVrxOD0pGVsfqGF8s3VPeY7hI2TxHFMqNA0IB/a2NLY7JTxYAKAP/11EJZt7xbq
# DLMgD1YDdGEzGpQijm3nAPCL2CebP/jmu90abJ2W425yglGHTI/nCBrwSpfRCgwz
# rfFelJaCKM6+35aFfwIDAQABo4IBSTCCAUUwHQYDVR0OBBYEFNLW58N4MGSG6ud7
# jWqgT92orfReMB8GA1UdIwQYMBaAFJ+nFV0AXmJdg/Tl0mWnG1M1GelyMF8GA1Ud
# HwRYMFYwVKBSoFCGTmh0dHA6Ly93d3cubWljcm9zb2Z0LmNvbS9wa2lvcHMvY3Js
# L01pY3Jvc29mdCUyMFRpbWUtU3RhbXAlMjBQQ0ElMjAyMDEwKDEpLmNybDBsBggr
# BgEFBQcBAQRgMF4wXAYIKwYBBQUHMAKGUGh0dHA6Ly93d3cubWljcm9zb2Z0LmNv
# bS9wa2lvcHMvY2VydHMvTWljcm9zb2Z0JTIwVGltZS1TdGFtcCUyMFBDQSUyMDIw
# MTAoMSkuY3J0MAwGA1UdEwEB/wQCMAAwFgYDVR0lAQH/BAwwCgYIKwYBBQUHAwgw
# DgYDVR0PAQH/BAQDAgeAMA0GCSqGSIb3DQEBCwUAA4ICAQAqncud4PSC1teb2H6n
# Ruy7sDiKK13FXJirVB4Tfwjdo2Mb+QL4j7wZ/k4G9P0CANHZFrDQcK0VFDTysrYu
# 8Z0Aha14acDZPsyIoPvAGRRhaHEuf7NckRjkfa/ylo1KyII8jbL9N9sJAqBPL8V4
# FNBjljv+1GHDOw127rZz5ZSTPoAPb2SA0v5yDgcpUMfxglPyp6cnPPoQpTtD9OGx
# 8Dwm2P+o1TPxBIy6I0T9RauulogVCvKwflfeLTcKAvnSG1rCjerSXmU1DNXOsAD/
# bsrSjgbX5mAbD7XTRMF/vawAWESFcn/BjjizxeWZb00aYSlkJA2rVtFlMM481aVW
# XdAbXPP5RzUiWTlgyHf/G7lCxHYWGIZuB13T3aI6Y8mEgn/ou40aiFJo8r0+i0P5
# GdNneWtxiR0CMKUfko+5s/73cwe1Wfp8BKXa270cicVQasFf5sRV7pFm+V7fNRXw
# Cu7anTOmga76zO7/2t+zOlibvphT+Q6Zd+B2qYsSn4xBaY+YzHpnycLW5cvJyhPx
# BCcb1oRYfhRzCADb2utI2EtGCjc2P2ii4LyR4QMb/n8cOweL9IqVTKKzzVk+zZJx
# V3vrp4LyuQXw0O30la6BcHdNAAAB9UC83zs3G9d+AlIfZLM97tMUNKWjbBpIirFx
# 6LTDFXVtZQd7hqzLYByjbjH0ujCCB3EwggVZoAMCAQICEzMAAAAVxedrngKbSZkA
# AAAAABUwDQYJKoZIhvcNAQELBQAwgYgxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpX
# YXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQg
# Q29ycG9yYXRpb24xMjAwBgNVBAMTKU1pY3Jvc29mdCBSb290IENlcnRpZmljYXRl
# IEF1dGhvcml0eSAyMDEwMB4XDTIxMDkzMDE4MjIyNVoXDTMwMDkzMDE4MzIyNVow
# fDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1Jl
# ZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEmMCQGA1UEAxMd
# TWljcm9zb2Z0IFRpbWUtU3RhbXAgUENBIDIwMTAwggIiMA0GCSqGSIb3DQEBAQUA
# A4ICDwAwggIKAoICAQDk4aZM57RyIQt5osvXJHm9DtWC0/3unAcH0qlsTnXIyjVX
# 9gF/bErg4r25PhdgM/9cT8dm95VTcVrifkpa/rg2Z4VGIwy1jRPPdzLAEBjoYH1q
# UoNEt6aORmsHFPPFdvWGUNzBRMhxXFExN6AKOG6N7dcP2CZTfDlhAnrEqv1yaa8d
# q6z2Nr41JmTamDu6GnszrYBbfowQHJ1S/rboYiXcag/PXfT+jlPP1uyFVk3v3byN
# pOORj7I5LFGc6XBpDco2LXCOMcg1KL3jtIckw+DJj361VI/c+gVVmG1oO5pGve2k
# rnopN6zL64NF50ZuyjLVwIYwXE8s4mKyzbnijYjklqwBSru+cakXW2dg3viSkR4d
# Pf0gz3N9QZpGdc3EXzTdEonW/aUgfX782Z5F37ZyL9t9X4C626p+Nuw2TPYrbqgS
# Uei/BQOj0XOmTTd0lBw0gg/wEPK3Rxjtp+iZfD9M269ewvPV2HM9Q07BMzlMjgK8
# QmguEOqEUUbi0b1qGFphAXPKZ6Je1yh2AuIzGHLXpyDwwvoSCtdjbwzJNmSLW6Cm
# gyFdXzB0kZSU2LlQ+QuJYfM2BjUYhEfb3BvR/bLUHMVr9lxSUV0S2yW6r1AFemzF
# ER1y7435UsSFF5PAPBXbGjfHCBUYP3irRbb1Hode2o+eFnJpxq57t7c+auIurQID
# AQABo4IB3TCCAdkwEgYJKwYBBAGCNxUBBAUCAwEAATAjBgkrBgEEAYI3FQIEFgQU
# KqdS/mTEmr6CkTxGNSnPEP8vBO4wHQYDVR0OBBYEFJ+nFV0AXmJdg/Tl0mWnG1M1
# GelyMFwGA1UdIARVMFMwUQYMKwYBBAGCN0yDfQEBMEEwPwYIKwYBBQUHAgEWM2h0
# dHA6Ly93d3cubWljcm9zb2Z0LmNvbS9wa2lvcHMvRG9jcy9SZXBvc2l0b3J5Lmh0
# bTATBgNVHSUEDDAKBggrBgEFBQcDCDAZBgkrBgEEAYI3FAIEDB4KAFMAdQBiAEMA
# QTALBgNVHQ8EBAMCAYYwDwYDVR0TAQH/BAUwAwEB/zAfBgNVHSMEGDAWgBTV9lbL
# j+iiXGJo0T2UkFvXzpoYxDBWBgNVHR8ETzBNMEugSaBHhkVodHRwOi8vY3JsLm1p
# Y3Jvc29mdC5jb20vcGtpL2NybC9wcm9kdWN0cy9NaWNSb29DZXJBdXRfMjAxMC0w
# Ni0yMy5jcmwwWgYIKwYBBQUHAQEETjBMMEoGCCsGAQUFBzAChj5odHRwOi8vd3d3
# Lm1pY3Jvc29mdC5jb20vcGtpL2NlcnRzL01pY1Jvb0NlckF1dF8yMDEwLTA2LTIz
# LmNydDANBgkqhkiG9w0BAQsFAAOCAgEAnVV9/Cqt4SwfZwExJFvhnnJL/Klv6lwU
# tj5OR2R4sQaTlz0xM7U518JxNj/aZGx80HU5bbsPMeTCj/ts0aGUGCLu6WZnOlNN
# 3Zi6th542DYunKmCVgADsAW+iehp4LoJ7nvfam++Kctu2D9IdQHZGN5tggz1bSNU
# 5HhTdSRXud2f8449xvNo32X2pFaq95W2KFUn0CS9QKC/GbYSEhFdPSfgQJY4rPf5
# KYnDvBewVIVCs/wMnosZiefwC2qBwoEZQhlSdYo2wh3DYXMuLGt7bj8sCXgU6ZGy
# qVvfSaN0DLzskYDSPeZKPmY7T7uG+jIa2Zb0j/aRAfbOxnT99kxybxCrdTDFNLB6
# 2FD+CljdQDzHVG2dY3RILLFORy3BFARxv2T5JL5zbcqOCb2zAVdJVGTZc9d/HltE
# AY5aGZFrDZ+kKNxnGSgkujhLmm77IVRrakURR6nxt67I6IleT53S0Ex2tVdUCbFp
# AUR+fKFhbHP+CrvsQWY9af3LwUFJfn6Tvsv4O+S3Fb+0zj6lMVGEvL8CwYKiexcd
# FYmNcP7ntdAoGokLjzbaukz5m/8K6TT4JDVnK+ANuOaMmdbhIurwJ0I9JZTmdHRb
# atGePu1+oDEzfbzL6Xu/OHBE0ZDxyKs6ijoIYn/ZcGNTTY3ugm2lBRDBcQZqELQd
# VTNYs6FwZvKhggNQMIICOAIBATCB+aGB0aSBzjCByzELMAkGA1UEBhMCVVMxEzAR
# BgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1p
# Y3Jvc29mdCBDb3Jwb3JhdGlvbjElMCMGA1UECxMcTWljcm9zb2Z0IEFtZXJpY2Eg
# T3BlcmF0aW9uczEnMCUGA1UECxMeblNoaWVsZCBUU1MgRVNOOkE5MzUtMDNFMC1E
# OTQ3MSUwIwYDVQQDExxNaWNyb3NvZnQgVGltZS1TdGFtcCBTZXJ2aWNloiMKAQEw
# BwYFKw4DAhoDFQAjHzqthPwO0GDckDMA6x54lIiMKqCBgzCBgKR+MHwxCzAJBgNV
# BAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4w
# HAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xJjAkBgNVBAMTHU1pY3Jvc29m
# dCBUaW1lLVN0YW1wIFBDQSAyMDEwMA0GCSqGSIb3DQEBCwUAAgUA7ZvPUTAiGA8y
# MDI2MDQyOTAwMjkwNVoYDzIwMjYwNDMwMDAyOTA1WjB3MD0GCisGAQQBhFkKBAEx
# LzAtMAoCBQDtm89RAgEAMAoCAQACAg6bAgH/MAcCAQACAhN/MAoCBQDtnSDRAgEA
# MDYGCisGAQQBhFkKBAIxKDAmMAwGCisGAQQBhFkKAwKgCjAIAgEAAgMHoSChCjAI
# AgEAAgMBhqAwDQYJKoZIhvcNAQELBQADggEBAGqs1AYf3ClRLcTbcp7qYycQszEz
# SZwiUet13wbNQkQTJ4x4S0m06I7kf0PQAN75O2HsPQ3HF7gR4LEqwX68ZQcGiKVY
# TT6MEe6hJirEBwaweAlL7QvoFeTl9CCmDkx0xtue25FZLb5QS6+Q7zmJ2lRVYTYG
# drRvf4Dul8+JsbkdwZIGl2diV4tKM/a5b4batsF6houB4kA7dGmIL50ARMk2BToS
# q+gBFAbv4FFKM8/Vaciy0Ik6bPI6SENcqxmNkl3NyGwblsjpngDjyOIUc7J/VjJn
# /XUCIJPmOfMcTGUtu6rfIVAlTw/bBzwnX7vfHI+cAaZrMjcymHtINiKFOPMxggQN
# MIIECQIBATCBkzB8MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQ
# MA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9u
# MSYwJAYDVQQDEx1NaWNyb3NvZnQgVGltZS1TdGFtcCBQQ0EgMjAxMAITMwAAAifV
# wIPDsS5XLQABAAACJzANBglghkgBZQMEAgEFAKCCAUowGgYJKoZIhvcNAQkDMQ0G
# CyqGSIb3DQEJEAEEMC8GCSqGSIb3DQEJBDEiBCD/QQMJhFyGILxjtrokMdWMbth5
# Ql2epjc/NcFt9XQtgjCB+gYLKoZIhvcNAQkQAi8xgeowgecwgeQwgb0EIOXnARo1
# oVIcOLJKDqlE0adq/jZ9TXdlnXWRcXGThBFyMIGYMIGApH4wfDELMAkGA1UEBhMC
# VVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNV
# BAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEmMCQGA1UEAxMdTWljcm9zb2Z0IFRp
# bWUtU3RhbXAgUENBIDIwMTACEzMAAAIn1cCDw7EuVy0AAQAAAicwIgQgpe3Xc30U
# Wty7bv+YxSBgq1FAR/rQBcVyN3Hr7H98XqUwDQYJKoZIhvcNAQELBQAEggIAlHRr
# ACY8Shp0EhnT/lRWQALA+s86a9iVJw+19ri5fODT/LIshMLtIV+XFqkL/oZJBLRN
# t7N+Hj0E84g9zc0+CBIMRQSNDW+GA0d06xVNHhFEkg6rYoVyFvn5r/GmZg63sGCx
# ZH4A9YksbbsbPrcHptlGDZO5qntUtFbumVleb0qzEKYqfXl6rldW7CuSoa9vkfcy
# WgfY1kLERX4N3kBzODP1z7U+6mv0Q7/bYwWRT0vIHFSBwDViRFOx5AE2yuHHZuKj
# /+6KozrS6HX+B3U512BzRhheFfM1hYvVbyjF2fiADdoXc/qN6EdGL2lMpZMA9OMo
# htnwIUCoAfoR7nj5/q4UgAgkdxYKDscCw3td+72zQ2TeXWfE6Ght39fhVKAVTpam
# ButmuYOVm1oFVE1vmqfT9wXJdoJtutOKc+pb+P/BATJhyQ9mXurmuh6UgvFYJlCt
# OpEt7GOEdoWETUuYq7/sSWo6uiHoCNArPmbgzYn+glVfkoKLcf/gittpT6ep4Dxk
# asC20gdnv9gujkmIRbXaSV9JLEHW9DHm/kLJaga/TTl4VJpZp1RDKUxWdVsLsgW4
# H9JzpMpsoRTfANWCFSerk59Yg32KU4acRKEgHUFZ6E6TKeamVXKsjLdLn4kmAl02
# Fmq/8kdvik0KuUuyWlP//RoLMfuRudUNrHBcZNU=
# SIG # End signature block
